# Define the compilers versions we wish to build the unit tests against
environment:
  matrix:
    - QTDIR: C:\Qt\5.6\mingw49_32
      MINGW: C:\Qt\Tools\mingw49_32
    - QTDIR: C:\Qt\5.7\msvc2013
    - QTDIR: C:\Qt\5.7\msvc2013_64
    - QTDIR: C:\Qt\5.7\msvc2015
    - QTDIR: C:\Qt\5.7\msvc2015_64
    - QTDIR: C:\Qt\5.9\msvc2017_64

configuration:
  - debug
  - release

# Workaround to get the project submodules
install:
  - git submodule update --init --recursive

# Ensure we have a make tool in the path to call
init:
  - '%QTDIR%\bin\qtenv2.bat'
  - set PATH=%PATH%;%QTDIR%\bin;%MINGW%\bin
  - if %QTDIR:_64=%==%QTDIR% ( set ARCH=x86 ) else set ARCH=x64
  - if %QTDIR:msvc=%==%QTDIR% set make=mingw32-make.exe
  - if not %QTDIR:msvc2013=%==%QTDIR% call "%ProgramFiles(x86)%\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" %ARCH%
  - if not %QTDIR:msvc2015=%==%QTDIR% call "%ProgramFiles(x86)%\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %ARCH%
  - if not %QTDIR:msvc2017=%==%QTDIR% call "%ProgramFiles(x86)%\Microsoft Visual Studio 15.0\VC\vcvarsall.bat" %ARCH%
  - if not %QTDIR:msvc=%==%QTDIR% set make=nmake.exe
  - if not %QTDIR:msvc=%==%QTDIR% %make% /? > nul

# Build the projects
build_script:
  - pushd unit
  - qmake -d -Wall unit_test.pro
  - '%make%'
  - popd

# Run the unit test executable
test_script:
  -

# Save the unit test executables
# TODO