environment:
  matrix:
    - QTDIR: C:\Qt\5.6\mingw49_32
      MINGW: C:\Qt\Tools\mingw49_32
    - QTDIR: C:\Qt\5.7\msvc2013
    - QTDIR: C:\Qt\5.7\msvc2013_64
    - QTDIR: C:\Qt\5.7\msvc2015
    - QTDIR: C:\Qt\5.7\msvc2015_64
    - QTDIR: C:\Qt\5.9\msvc2017_64

configuration:
  - debug
  - release

init:
  - set PATH=%PATH%;%QTDIR%\bin;%MINGW%\bin

build_script:
  - pushd unit
  - qmake unit_test.pro
  - make
  - popd

test_script:
  -