language: cpp
os: linux
compiler: gcc
sudo: required
dist: trusty

# Add encrypted API key
env:
  global:
    - secure: O+4RPv9Vh/yAqO/kumLdssGQGDzjpgQjEJbMAI4KKJG5s0IdOkcPfekffeU301czikQTIogbQsH3E9QbkRMbI3J4UKvRdbTpdzb/NjSNUN14qCbxoFhEp85HUCJX2/gUt7XJFsuJM6ZRi9UkFZxTiIrHjYkg1lWVjqO+T3K8TTyq92v00edHYjQnFV6/62fRJmfKUoAa2ExyRpd2f0B+P05mIy0bYktInCEv2ct6E5Rg3aOWf+WokwpP0ox9G66EG1nxM/Uh603OmYve0lXLez4S76KYBbrWbDYpXazsxC9mSCk7l5GQ9h2xpbFVgBrQEanZxyq/0mzY0mfBNDcUMx2KWkQxqSnBMBFWOw3CDZJd5y8PflaTDEOvNtYHEh/CsnAEKpJsxK92gcTi70HN+sIXo3yDNVKyWSP7lYszI95g0xIGny8OW/AHFiBGu0g0MIzv/jK87M06DqnjaRY5MyYwc5pSaH27xpopVMFUDbBxCrneILXxW+po9cBIc26Y7P2SEFoKqd72FLVZt2NYGT48e/eLG6/dYiowqXI83ViptZj5LFJjlxuPrtlfbGhevRMWPzynjAl42R8BAeuQIoZQodPd903DSW3882Lsmszy7Gwpv0Bz+J469kDiFsWP49iROPSXezzmfi65wkoakUWMFP98aSIfYVHFhQIwkgs=
    - secure:NEQuglPuppjWzrPlUt0qNBtFYwDnEFPIFC/0dl5seC9vyOR1ZmCX5ZEGiS5owDK74BlTh80FUGBK8qlpWfvdfK+nD53wGvyr34Uf37vRP3DxcAVFETHaY+qRwgMhhS2+oSas7fPo54lQF/yDUneicFQzrR5zHwyhpBAUUtsC4GsGnyZuXHISwarFTJ00jE/lS6LMmmXSxBDRmd4N0r7zt6nXVxVyj3yN/rOsCnZ+YXN8Ll0nJQoBQH6yEF/aTwhjW4cHPhFouK8Ne6eK99Q7Gh2RXZanLgUaUwIkrBVf/r0PmGMruuWPSa0YAIPMgXXE6Db0RoH/tQ+FUAdAkhxjR6g9zjc74ys6L7ldHYpE5VD/+OfCfN5zCFfXvTV8+njbgxgWjHGAPmE1AXZk402ExptkU3l1aE+f6xe9iAd2FU4MlUebZbIdrdz2i+uQW3VxgPJj0KifgZk/1Ujx2/3QeH9S+icrP1el9u9aRyZ7KJgo77Swe7QJxu8VHTUDKEuqWvxu3tJYx1xAjkB61j14t2Wh9dI5rZk1SRnNXAbpEM9v+nk8feleTdo5Z40ygcRQR+Ho+/DnG+JsqBegxT9I1eKd1ESPypc+u9695HdGIADAJ6VgS4MJCLSRxZARhRxPozNnAvQLNDiEDj2cEYy9FcSp5XjuGW1udvhfnY0CrYs="

# Get the latest version of the Geometrize library submodule, and push it to the remote (if necessary)
before_install:
  - chmod +x ./travis_update_geometrize_submodule.sh
  - ./travis_update_geometrize_submodule.sh

# Install g++
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
  coverity_scan:
    project:
      name: "Tw1ddle/geometrize-lib-unit-tests"
      description: "Travis build bot submitting Coverity build"
    build_command_prepend: "pushd unit"
    build_command_prepend: "qmake"
    build_command: "make"
    branch_pattern: master

# Install necessary Qt files
install:
  - sudo apt-get install -y qt5-default qttools5-dev-tools

# Build and run the unit tests
script:
  - pushd unit
  - qmake unit_test.pro
  - make
  - popd