language: cpp
os: linux
compiler: gcc
sudo: required
dist: trusty

# Add encrypted API key
env:
  global:
    - secure: O+4RPv9Vh/yAqO/kumLdssGQGDzjpgQjEJbMAI4KKJG5s0IdOkcPfekffeU301czikQTIogbQsH3E9QbkRMbI3J4UKvRdbTpdzb/NjSNUN14qCbxoFhEp85HUCJX2/gUt7XJFsuJM6ZRi9UkFZxTiIrHjYkg1lWVjqO+T3K8TTyq92v00edHYjQnFV6/62fRJmfKUoAa2ExyRpd2f0B+P05mIy0bYktInCEv2ct6E5Rg3aOWf+WokwpP0ox9G66EG1nxM/Uh603OmYve0lXLez4S76KYBbrWbDYpXazsxC9mSCk7l5GQ9h2xpbFVgBrQEanZxyq/0mzY0mfBNDcUMx2KWkQxqSnBMBFWOw3CDZJd5y8PflaTDEOvNtYHEh/CsnAEKpJsxK92gcTi70HN+sIXo3yDNVKyWSP7lYszI95g0xIGny8OW/AHFiBGu0g0MIzv/jK87M06DqnjaRY5MyYwc5pSaH27xpopVMFUDbBxCrneILXxW+po9cBIc26Y7P2SEFoKqd72FLVZt2NYGT48e/eLG6/dYiowqXI83ViptZj5LFJjlxuPrtlfbGhevRMWPzynjAl42R8BAeuQIoZQodPd903DSW3882Lsmszy7Gwpv0Bz+J469kDiFsWP49iROPSXezzmfi65wkoakUWMFP98aSIfYVHFhQIwkgs=

# Get the latest version of the Geometrize library submodule, and push it to the remote (if necessary)
before_install:
  - chmod +x ./travis_update_geometrize_submodule.sh
  - ./travis_update_geometrize_submodule.sh

# Install g++
addons:
  apt:
    packages:
      - gcc-5
      - g++-5

# Install necessary Qt files
install:
  - sudo apt-get install -y qt5-default qttools5-dev-tools

# Build and run the unit tests
script:
  - pushd unit
  - qmake unit_test.pro
  - make
  - popd